name = "adarsh-research-and-publication-house"
compatibility_date = "2024-03-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "adarsh_db"
database_id = "3858796b-3e95-4846-862a-e183e6ea70f3"
